### ISSUE TITLE
Local Minitest is failing

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-fields#18]
I feel like I saw this with some other repos in the past, but now I'm only seeing it with `bullet_train-fields`. I won't spend too much time trying to figure it out if it isn't high priority, but it just bothered me a bit:

```
> bundle exec rails test
/home/gazayas/work/bt/bullet_train-fields/lib/bullet_train/fields/engine.rb:5:in `block in <class:Engine>': undefined method `linked_gems' for BulletTrain:Module (NoMethodError)

        BulletTrain.linked_gems << "bullet_train-fields"
                   ^^^^^^^^^^^^
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
	from /home/gazayas/work/bt/bullet_train-fields/test/dummy/config/environment.rb:5:in `<top (required)>'
	from /home/gazayas/work/bt/bullet_train-fields/test/test_helper.rb:4:in `require_relative'
	from /home/gazayas/work/bt/bullet_train-fields/test/test_helper.rb:4:in `<top (required)>'
	from /home/gazayas/work/bt/bullet_train-fields/test/bullet_train/fields_test.rb:1:in `require'
	from /home/gazayas/work/bt/bullet_train-fields/test/bullet_train/fields_test.rb:1:in `<top (required)>'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `require'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `each'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:47:in `load_tests'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/test_unit/runner.rb:40:in `run'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/engine/commands.rb:9:in `require'
	from /home/gazayas/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/engine/commands.rb:9:in `<top (required)>'
	from bin/rails:14:in `require'
	from bin/rails:14:in `<main>'

```

**Comment by gazayas** [comment]
Seeing code like this in `bullet_train-super_scaffolding`:
```ruby
initializer "bullet_train.super_scaffolding.register" do |app|
  # Older versions of Bullet Train have a `BulletTrain` module, but it doesn't have `linked_gems`.
  if BulletTrain.respond_to?(:linked_gems)
    BulletTrain.linked_gems << "bullet_train-super_scaffolding"
  end
end
```
